// Seed personas for the harness. Twelve YC SS 2026 archetypes covering
// the cohort distribution: hardtech, AI infra, fintech, devtools, design,
// climate, healthtech, marketplace, India founder, Latam founder, solo
// hacker, and a returning-founder "voice of skepticism" persona.
//
// Each persona is a stable bundle of identity + intent + decision style.
// The runtime drives them through signup → onboarding → drops → intros
// → meetings, against the live app at http://localhost:3030.
//
// Adding more personas: append to PERSONAS. The runtime auto-discovers
// the full list. Keep ids stable so persisted state files (harness/state/<id>.json)
// stay valid across runs.

import type { Persona } from "../types";

export const PERSONAS: Persona[] = [
  {
    id: "p_priya_fintech",
    identity: {
      name: "Priya Reddy",
      email: "priya@harness.local",
      location: "Bangalore, going to SF",
      oneLine: "Building cross-border payments rail for India to US founders.",
      publicLink: "linkedin.com/in/priya-reddy-harness",
    },
    intent: {
      building: "Cross-border payments rail. Settlement under 4 hours, INR↔USD, KYC handled at the API layer.",
      looking_for: "Fintech operators who have shipped real money movement. Engineers who think in compliance constraints.",
      can_help_with: "India banking ops, RBI guidelines, US treasury integrations, hiring in Bangalore.",
      talk_to_me_if: "You build infra that moves money and you sweat the boring details.",
      tags: ["fintech", "india", "payments", "infra", "cofounder"],
      going_to_sf: true,
      attended_india: true,
      remote_global: false,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "picky",
    cadence: { pollMinSec: 600, pollMaxSec: 1800, actionRate: 0.7 },
    affinityHints: { p_marcus_devops: 0.4, p_aiko_design: 0.2, p_diego_latam: 0.6 },
  },
  {
    id: "p_marcus_devops",
    identity: {
      name: "Marcus Chen",
      email: "marcus@harness.local",
      location: "San Francisco",
      oneLine: "Open-source observability for AI agent runtimes.",
      publicLink: "github.com/marcus-chen-harness",
    },
    intent: {
      building: "Trace, debug, and replay AI agent runs across providers. Open core, hosted as the upgrade.",
      looking_for: "Cofounders who lead with developer experience. Anyone who has shipped infra at scale.",
      can_help_with: "Distributed tracing, OTEL, Kubernetes, agent runtime architecture, OSS go-to-market.",
      talk_to_me_if: "You ship developer tools and you think docs are a feature.",
      tags: ["devtools", "ai-agents", "observability", "open-source", "cofounder", "sf"],
      going_to_sf: true,
      attended_india: false,
      remote_global: false,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "eager",
    cadence: { pollMinSec: 180, pollMaxSec: 900, actionRate: 0.85 },
    affinityHints: { p_priya_fintech: 0.3, p_aiko_design: 0.5, p_kai_solo: 0.6 },
  },
  {
    id: "p_aiko_design",
    identity: {
      name: "Aiko Tanaka",
      email: "aiko@harness.local",
      location: "Tokyo, going to SF",
      oneLine: "Design tooling that ships interfaces from a paragraph of intent.",
      publicLink: "aiko.studio",
    },
    intent: {
      building: "Designer-led codegen. Take a brand voice and a flow doc, output a working Next.js app with motion baked in.",
      looking_for: "Frontend engineers who care about typography. Designers who can code.",
      can_help_with: "Design systems, motion design, brand work, reducing visual noise in dashboards.",
      talk_to_me_if: "You think most SaaS UI is ugly and you have an opinion about why.",
      tags: ["design", "frontend", "ai-agents", "japan", "solo"],
      going_to_sf: true,
      attended_india: false,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "chatty",
    cadence: { pollMinSec: 300, pollMaxSec: 1500, actionRate: 0.6 },
    affinityHints: { p_marcus_devops: 0.5, p_kai_solo: 0.4, p_priya_fintech: 0.2 },
  },
  {
    id: "p_diego_latam",
    identity: {
      name: "Diego Alvarez",
      email: "diego@harness.local",
      location: "Mexico City, going to SF",
      oneLine: "Latam-first business banking, Spanish-native compliance flows.",
    },
    intent: {
      building: "Mercury for Latam SMEs. KYC localized to MX, AR, CO. USD treasury for dollarized founders.",
      looking_for: "Operators who scaled financial products in emerging markets. Engineers comfortable with bank rails.",
      can_help_with: "Mexico banking partners, CONDUSEF compliance, Spanish-language UX, hiring in CDMX.",
      talk_to_me_if: "You are building for Latam or for emerging-market founders.",
      tags: ["fintech", "latam", "emerging-markets", "payments", "cofounder"],
      going_to_sf: true,
      attended_india: false,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "responsive",
    cadence: { pollMinSec: 240, pollMaxSec: 1200, actionRate: 0.8 },
    affinityHints: { p_priya_fintech: 0.7, p_marcus_devops: 0.2, p_kai_solo: 0.3 },
  },
  {
    id: "p_kai_solo",
    identity: {
      name: "Kai Nakamura",
      email: "kai@harness.local",
      location: "Seattle",
      oneLine: "Solo hacker shipping a research-paper-to-explainer tool.",
      publicLink: "kainakamura.dev",
    },
    intent: {
      building: "Take an arxiv URL, output a 5-minute explainer with diagrams and an audio track. For technical PMs and ICs who can not read 40 papers a week.",
      looking_for: "Technical cofounders. AI infra people. Anyone who has built a content-gen product that is not slop.",
      can_help_with: "ML papers, diffusion fine-tuning, fast prototyping, audio synthesis, voice cloning.",
      talk_to_me_if: "You ship alone and you respect velocity.",
      tags: ["ai-agents", "research", "media", "solo", "undergrad"],
      going_to_sf: false,
      attended_india: false,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: false,
    },
    decisionStyle: "minimal",
    cadence: { pollMinSec: 60, pollMaxSec: 600, actionRate: 0.9 },
    affinityHints: { p_aiko_design: 0.5, p_marcus_devops: 0.7, p_lena_climate: 0.3 },
  },
  {
    id: "p_lena_climate",
    identity: {
      name: "Lena Voss",
      email: "lena@harness.local",
      location: "Berlin, going to SF",
      oneLine: "Battery analytics for industrial fleets. Predictive failure on commercial EV trucks.",
    },
    intent: {
      building: "Cell-level analytics for commercial EV fleets. Predict failure 6 weeks out, save the fleet operator $30k per truck.",
      looking_for: "Hardware founders, embedded engineers, ML people who care about real-world signals.",
      can_help_with: "Battery chemistry, embedded firmware, German manufacturing partners, industrial sales.",
      talk_to_me_if: "You build atoms-not-bits and you still ship fast.",
      tags: ["climate", "hardtech", "ml", "europe", "cofounder"],
      going_to_sf: true,
      attended_india: false,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "picky",
    cadence: { pollMinSec: 900, pollMaxSec: 2400, actionRate: 0.5 },
  },
  {
    id: "p_omar_health",
    identity: {
      name: "Omar Hassan",
      email: "omar@harness.local",
      location: "London, going to SF",
      oneLine: "AI medical scribe trained on UK NHS workflows.",
    },
    intent: {
      building: "Ambient medical scribe for UK GPs. Trained on NHS guidelines, integrates with EMIS and SystmOne.",
      looking_for: "Founders who understand healthcare regulatory work. Engineers comfortable with audio + privacy.",
      can_help_with: "NHS sales, GDPR for medical data, ambient ASR, clinical NLP.",
      talk_to_me_if: "You build for clinicians and you respect that they are tired.",
      tags: ["healthtech", "ai-agents", "europe", "regulated"],
      going_to_sf: true,
      attended_india: false,
      remote_global: false,
      open_to_async: false,
      open_to_in_person: true,
    },
    decisionStyle: "scheduler",
    cadence: { pollMinSec: 1200, pollMaxSec: 3600, actionRate: 0.4 },
  },
  {
    id: "p_yusuf_marketplace",
    identity: {
      name: "Yusuf Khan",
      email: "yusuf@harness.local",
      location: "Lahore, going to SF",
      oneLine: "B2B marketplace for surplus textile inventory in South Asia.",
    },
    intent: {
      building: "Excess inventory marketplace for textile mills. Sellers list dead stock, buyers (small fashion brands) bid in lots.",
      looking_for: "Marketplace operators. Anyone with supply-side acquisition experience.",
      can_help_with: "Pakistan/India textile supply chain, marketplace liquidity strategies, B2B sales in emerging markets.",
      talk_to_me_if: "You have built a marketplace that crossed the cold-start.",
      tags: ["marketplace", "emerging-markets", "supply-chain", "india", "cofounder"],
      going_to_sf: true,
      attended_india: true,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "eager",
    cadence: { pollMinSec: 300, pollMaxSec: 1200, actionRate: 0.75 },
  },
  {
    id: "p_sara_b2b",
    identity: {
      name: "Sara Lim",
      email: "sara@harness.local",
      location: "Singapore, going to SF",
      oneLine: "Procurement-AI for mid-market manufacturers. Quote-to-purchase in 3 hours.",
      publicLink: "linkedin.com/in/sara-lim-harness",
    },
    intent: {
      building: "Procurement copilot. Pulls supplier specs, generates RFQs, negotiates draft pricing, hands the human a comparison table.",
      looking_for: "Founders who have sold into manufacturing. AI engineers who care about high-stakes business workflows.",
      can_help_with: "Supply-chain ops, procurement domain knowledge, APAC enterprise sales.",
      talk_to_me_if: "You sell to operators not engineers.",
      tags: ["b2b", "ai-agents", "supply-chain", "asia", "enterprise"],
      going_to_sf: true,
      attended_india: false,
      remote_global: false,
      open_to_async: false,
      open_to_in_person: true,
    },
    decisionStyle: "responsive",
    cadence: { pollMinSec: 450, pollMaxSec: 1800, actionRate: 0.65 },
  },
  {
    id: "p_jordan_ghoster",
    identity: {
      name: "Jordan Park",
      email: "jordan@harness.local",
      location: "Los Angeles, going to SF",
      oneLine: "Solo founder, can't decide what I'm building yet.",
    },
    intent: {
      building: "Exploring a few ideas around AI for screenwriters. Not committed to any single direction.",
      looking_for: "People who have made the switch from explore to commit. Cofounder-shaped collaborators.",
      can_help_with: "Game design instincts, narrative tooling, LA media-industry contacts.",
      talk_to_me_if: "You have shipped something solo and survived.",
      tags: ["ai-agents", "media", "solo", "exploring"],
      going_to_sf: true,
      attended_india: false,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "ghoster",
    cadence: { pollMinSec: 1800, pollMaxSec: 7200, actionRate: 0.2 },
  },
  {
    id: "p_anh_undergrad",
    identity: {
      name: "Anh Tran",
      email: "anh@harness.local",
      location: "Boston",
      oneLine: "MIT undergrad. Building a research paper deep-search tool for grad students.",
      publicLink: "anhtran.mit.edu",
    },
    intent: {
      building: "Semantic search across paywalled research, with citation graph traversal. Targeting graduate students who write lit reviews.",
      looking_for: "Technical cofounders, ML researchers, anyone who has launched a tool to academics.",
      can_help_with: "Research-tools UX, citation parsing, academic email outreach playbooks.",
      talk_to_me_if: "You like building for niches that hate paying.",
      tags: ["research", "ai-agents", "undergrad", "education", "cofounder"],
      going_to_sf: true,
      attended_india: false,
      remote_global: true,
      open_to_async: true,
      open_to_in_person: true,
    },
    decisionStyle: "eager",
    cadence: { pollMinSec: 120, pollMaxSec: 600, actionRate: 0.9 },
  },
  {
    id: "p_rohan_skeptic",
    identity: {
      name: "Rohan Mehta",
      email: "rohan@harness.local",
      location: "New York",
      oneLine: "Returning founder. Ate one already. Skeptical of every new app, will tell you why yours sucks.",
      publicLink: "linkedin.com/in/rohan-mehta-skeptic",
    },
    intent: {
      building: "Real-time financial-data API for fintech apps. Boring, profitable, not AI-flavored.",
      looking_for: "Fellow second-time founders. People who survived their first one.",
      can_help_with: "Brutal honesty, fundraising war stories, NY fintech contacts.",
      talk_to_me_if: "You want a sparring partner who will not blow smoke.",
      tags: ["fintech", "second-time", "infra", "nyc"],
      going_to_sf: true,
      attended_india: false,
      remote_global: false,
      open_to_async: false,
      open_to_in_person: true,
    },
    decisionStyle: "picky",
    cadence: { pollMinSec: 1500, pollMaxSec: 4500, actionRate: 0.3 },
  },
];

export function findPersona(id: string): Persona | undefined {
  return PERSONAS.find((p) => p.id === id);
}
