"use client";
import { useEffect, useRef, useState } from "react";

// FounderGraphHero — the big version. Replaces the 9-node star pattern
// with a 30-node clustered network: AI-infra, biotech, devtools,
// climate/hardtech, agents, fintech, ml-research, policy. Many
// people-to-people edges (not just YOU-to-others) so the graph reads
// as cohort fabric.
//
// One narrative path is highlighted with animated dash-draw:
// YOU → bridge node (AI-agents friend) → bridge node (cross-cluster
// peer) → TARGET (Maya Chen, ML researcher with voice-agents focus).
// A quote bubble floats over the highlighted path: "i want someone
// who can ship the routing layer for voice agents." A small profile
// chip floats next to the target showing why she's the answer.
//
// Visual register: big SVG (viewBox 1600x900), responsive via
// width="100%" h-auto. No three.js — pure SVG so it stays selectable,
// screen-readable, and ~3KB (vs the framer-canvas equivalent). All
// motion is CSS keyframes (stroke-dasharray for the path draw, slow
// pulse for the YOU node, holo shimmer for the target).
//
// Accessibility: role="img", aria-label describes the graph. The
// quote text is rendered as real DOM (foreignObject) so it's
// selectable and screen-reader-friendly.

type Node = {
  id: string;
  x: number;
  y: number;
  label: string;
  tag?: string;
  cluster: ClusterId;
};

type ClusterId =
  | "you"
  | "ai-infra"
  | "biotech"
  | "devtools"
  | "climate"
  | "hardtech"
  | "ai-agents"
  | "fintech"
  | "ml-research"
  | "policy";

// Cluster positioning is hand-tuned, not force-directed. Force-directed
// looked random; clusters by industry telegraph "the cohort breaks into
// families and you find someone via cross-family edges."
const NODES: Node[] = [
  // === YOU node, center ===
  { id: "you", x: 760, y: 450, label: "YOU", cluster: "you" },

  // === Highlighted path bridges (between YOU and target) ===
  { id: "p1", x: 920, y: 390, label: "AT", tag: "agents", cluster: "ai-agents" },
  { id: "p2", x: 1090, y: 340, label: "SK", tag: "ai-infra", cluster: "ai-infra" },
  // === Target: Maya Chen, ML researcher, voice agents ===
  { id: "target", x: 1280, y: 280, label: "MC", tag: "ml-research", cluster: "ml-research" },

  // === AI-infra cluster (top-left of YOU) ===
  { id: "ai1", x: 600, y: 280, label: "KS", tag: "ai-infra", cluster: "ai-infra" },
  { id: "ai2", x: 480, y: 380, label: "RK", tag: "ai-infra", cluster: "ai-infra" },
  { id: "ai3", x: 640, y: 180, label: "JD", tag: "ai-infra", cluster: "ai-infra" },
  { id: "ai4", x: 350, y: 250, label: "BL", tag: "ai-infra", cluster: "ai-infra" },

  // === Biotech cluster (top-right) ===
  { id: "bio1", x: 1380, y: 160, label: "DR", tag: "biotech", cluster: "biotech" },
  { id: "bio2", x: 1500, y: 280, label: "EM", tag: "biotech", cluster: "biotech" },
  { id: "bio3", x: 1280, y: 100, label: "NS", tag: "biotech", cluster: "biotech" },

  // === Climate / hardtech (bottom-left) ===
  { id: "ht1", x: 280, y: 540, label: "LV", tag: "climate", cluster: "climate" },
  { id: "ht2", x: 380, y: 660, label: "JK", tag: "hardtech", cluster: "hardtech" },
  { id: "ht3", x: 180, y: 620, label: "FW", tag: "hardtech", cluster: "hardtech" },
  { id: "ht4", x: 460, y: 740, label: "MG", tag: "climate", cluster: "climate" },

  // === Devtools (bottom-right) ===
  { id: "dt1", x: 1080, y: 660, label: "ML", tag: "devtools", cluster: "devtools" },
  { id: "dt2", x: 1240, y: 600, label: "AC", tag: "devtools", cluster: "devtools" },
  { id: "dt3", x: 1380, y: 720, label: "LM", tag: "devtools", cluster: "devtools" },
  { id: "dt4", x: 1180, y: 760, label: "SS", tag: "devtools", cluster: "devtools" },

  // === Agents cluster (center-bottom) ===
  { id: "ag1", x: 720, y: 620, label: "OY", tag: "agents", cluster: "ai-agents" },
  { id: "ag2", x: 850, y: 720, label: "TY", tag: "agents", cluster: "ai-agents" },
  { id: "ag3", x: 600, y: 720, label: "AI", tag: "agents", cluster: "ai-agents" },

  // === Fintech (left-mid) ===
  { id: "ft1", x: 180, y: 400, label: "PR", tag: "fintech", cluster: "fintech" },
  { id: "ft2", x: 300, y: 460, label: "MR", tag: "fintech", cluster: "fintech" },

  // === ML-research peers (around target) ===
  { id: "ml1", x: 1430, y: 380, label: "TC", tag: "ml-research", cluster: "ml-research" },
  { id: "ml2", x: 1180, y: 200, label: "NK", tag: "ml-research", cluster: "ml-research" },

  // === Policy ===
  { id: "pol1", x: 1500, y: 460, label: "NN", tag: "policy", cluster: "policy" },
  { id: "pol2", x: 1380, y: 540, label: "TZ", tag: "policy", cluster: "policy" },
];

// Edges. Mix of intra-cluster (founders that know each other within
// their family) and cross-cluster (the bridges that compound the
// graph). Generated by hand — random edges read as noise.
const EDGES: { from: string; to: string }[] = [
  // YOU's existing weak ties (faint)
  { from: "you", to: "ai1" },
  { from: "you", to: "ai2" },
  { from: "you", to: "ag1" },
  { from: "you", to: "ag3" },
  { from: "you", to: "ft1" },
  { from: "you", to: "ht1" },
  { from: "you", to: "p1" }, // bridge1 (highlighted later)

  // AI-infra intra-cluster
  { from: "ai1", to: "ai2" },
  { from: "ai1", to: "ai3" },
  { from: "ai2", to: "ai4" },
  { from: "ai3", to: "ai4" },
  { from: "ai1", to: "p2" }, // ai-infra ↔ bridge2

  // Biotech intra-cluster
  { from: "bio1", to: "bio2" },
  { from: "bio1", to: "bio3" },
  { from: "bio2", to: "bio3" },
  { from: "bio2", to: "ml1" }, // biotech ↔ ml-research

  // Devtools intra
  { from: "dt1", to: "dt2" },
  { from: "dt1", to: "dt4" },
  { from: "dt2", to: "dt3" },
  { from: "dt3", to: "dt4" },
  { from: "dt2", to: "pol2" },

  // Climate / hardtech
  { from: "ht1", to: "ht2" },
  { from: "ht1", to: "ht3" },
  { from: "ht2", to: "ht4" },
  { from: "ht3", to: "ht4" },
  { from: "ht1", to: "ft2" },

  // Agents
  { from: "ag1", to: "ag2" },
  { from: "ag1", to: "ag3" },
  { from: "ag2", to: "ag3" },
  { from: "ag1", to: "p1" }, // agents ↔ bridge1
  { from: "ag1", to: "dt1" }, // agents ↔ devtools

  // Fintech
  { from: "ft1", to: "ft2" },
  { from: "ft2", to: "pol1" },

  // ML-research
  { from: "ml1", to: "ml2" },
  { from: "ml1", to: "target" }, // ml-research ↔ target
  { from: "ml2", to: "target" },
  { from: "ml2", to: "p2" }, // ml-research ↔ bridge2

  // Policy intra
  { from: "pol1", to: "pol2" },
  { from: "pol1", to: "ml1" },

  // Cross-cluster bridges (the compounding fabric)
  { from: "ai3", to: "bio3" },
  { from: "bio2", to: "pol1" },
  { from: "dt4", to: "ag2" },
  { from: "ht1", to: "ai2" },
  { from: "ft2", to: "you" },
];

// The narrative path: YOU → bridge1 → bridge2 → target. These edges
// are what gets the dash-draw animation + accent stroke.
const HIGHLIGHTED_PATH: { from: string; to: string }[] = [
  { from: "you", to: "p1" },
  { from: "p1", to: "p2" },
  { from: "p2", to: "target" },
];

const HIGHLIGHTED_NODE_IDS = new Set(["you", "p1", "p2", "target"]);

const QUOTE_TEXT =
  "i want someone who can ship the routing layer for voice agents.";

const TARGET_PROFILE = {
  name: "Maya Chen",
  role: "ML researcher",
  tags: ["ex-Anthropic", "voice agents", "5y CUDA"],
  matchScore: 96,
};

export function FounderGraphHero(): React.JSX.Element {
  // Path-draw progress: 0 → 1 over ~3.2s after mount, then loops slowly
  // for ambient pulse. We control via a `revealed` state toggled by an
  // IntersectionObserver so the animation only runs once the section
  // scrolls into view.
  const wrapperRef = useRef<HTMLDivElement>(null);
  const [revealed, setRevealed] = useState(false);
  const nodeMap = new Map(NODES.map((n) => [n.id, n]));

  useEffect(() => {
    const el = wrapperRef.current;
    if (!el || typeof window === "undefined") return;
    const reduce = window.matchMedia(
      "(prefers-reduced-motion: reduce)"
    ).matches;
    if (reduce) {
      setRevealed(true);
      return;
    }
    const obs = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            setRevealed(true);
            obs.disconnect();
          }
        }
      },
      { threshold: 0.15 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  // Quote bubble position: midpoint of the highlighted path.
  // YOU (760, 450) → p1 (920, 390) → p2 (1090, 340) → target (1280, 280)
  // Midpoint of the middle edge (p1 → p2) = (1005, 365). Bubble sits
  // slightly above so it doesn't overlap edges.
  const QUOTE_X = 760;
  const QUOTE_Y = 540;
  const TARGET_CHIP_X = 1310;
  const TARGET_CHIP_Y = 110;

  return (
    <div ref={wrapperRef} className="relative w-full">
      <svg
        viewBox="0 0 1600 900"
        className="w-full h-auto block"
        role="img"
        aria-label={`Founder graph: 30 builder nodes across 8 industry clusters in the YC Startup School 2026 cohort. A highlighted path animates from YOU through two bridge nodes to the target match, an ML researcher named Maya Chen working on voice agents. The quote on the path reads: ${QUOTE_TEXT}`}
      >
        <defs>
          <radialGradient id="fghYouGlow" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#FF6600" stopOpacity="0.32" />
            <stop offset="60%" stopColor="#FF6600" stopOpacity="0.08" />
            <stop offset="100%" stopColor="#FF6600" stopOpacity="0" />
          </radialGradient>
          <radialGradient id="fghTargetGlow" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#FF6600" stopOpacity="0.40" />
            <stop offset="55%" stopColor="#FF6600" stopOpacity="0.10" />
            <stop offset="100%" stopColor="#FF6600" stopOpacity="0" />
          </radialGradient>
          <filter id="fghSoft" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur in="SourceGraphic" stdDeviation="6" />
          </filter>
        </defs>

        {/* Faint orbital guides under YOU + ambient layout cue */}
        <circle
          cx="760"
          cy="450"
          r="260"
          fill="none"
          stroke="#16140F"
          strokeOpacity="0.06"
          strokeDasharray="1 8"
          strokeWidth="1"
        />
        <circle
          cx="760"
          cy="450"
          r="380"
          fill="none"
          stroke="#16140F"
          strokeOpacity="0.04"
          strokeDasharray="1 10"
          strokeWidth="1"
        />

        {/* YOU glow */}
        <circle cx="760" cy="450" r="160" fill="url(#fghYouGlow)" />
        {/* Target glow */}
        <circle cx="1280" cy="280" r="140" fill="url(#fghTargetGlow)" />

        {/* === ALL EDGES (faint background fabric) ===
            Bumped opacity 0.13 -> 0.22 + width 0.9 -> 1.1 + dasharray
            tightened so every edge actually reads at 1440px. Was barely
            visible before (founder flagged invisible lines). */}
        <g className="fgh-edges-bg">
          {EDGES.map((e, i) => {
            const a = nodeMap.get(e.from);
            const b = nodeMap.get(e.to);
            if (!a || !b) return null;
            return (
              <line
                key={`bg-${i}`}
                x1={a.x}
                y1={a.y}
                x2={b.x}
                y2={b.y}
                stroke="#16140F"
                strokeOpacity="0.22"
                strokeWidth="1.1"
                strokeLinecap="round"
                strokeDasharray="2 4"
              />
            );
          })}
        </g>

        {/* === HIGHLIGHTED PATH — animates dash-draw on reveal === */}
        <g className={"fgh-edges-hl " + (revealed ? "fgh-revealed" : "")}>
          {HIGHLIGHTED_PATH.map((e, i) => {
            const a = nodeMap.get(e.from);
            const b = nodeMap.get(e.to);
            if (!a || !b) return null;
            // Compute the segment length so dasharray is exact (no
            // pre-fill on first paint).
            const len = Math.hypot(b.x - a.x, b.y - a.y);
            return (
              <line
                key={`hl-${i}`}
                x1={a.x}
                y1={a.y}
                x2={b.x}
                y2={b.y}
                stroke="#FF6600"
                strokeOpacity="0.9"
                strokeWidth="2.8"
                strokeLinecap="round"
                style={{
                  strokeDasharray: `${len}`,
                  strokeDashoffset: revealed ? 0 : len,
                  transition: `stroke-dashoffset 1.2s cubic-bezier(0.16, 1, 0.3, 1) ${i * 0.5}s`,
                }}
              />
            );
          })}
        </g>

        {/* === ALL NODES === */}
        <g className="fgh-nodes">
          {NODES.map((n) => {
            const isYou = n.id === "you";
            const isTarget = n.id === "target";
            const onPath = HIGHLIGHTED_NODE_IDS.has(n.id);
            const radius = isYou ? 36 : isTarget ? 32 : onPath ? 24 : 18;
            return (
              <g key={n.id} transform={`translate(${n.x} ${n.y})`}>
                {isYou ? (
                  <>
                    <circle
                      r={radius + 8}
                      fill="#F4F1DB"
                      stroke="#FF6600"
                      strokeWidth="1.5"
                    />
                    <circle r={radius} fill="#FF6600" />
                    <text
                      textAnchor="middle"
                      dy="0.32em"
                      className="font-mono"
                      fontSize="11"
                      fontWeight="600"
                      fill="#F4F1DB"
                      style={{ letterSpacing: "0.18em" }}
                    >
                      YOU
                    </text>
                  </>
                ) : isTarget ? (
                  <>
                    <circle
                      r={radius + 6}
                      fill="#F4F1DB"
                      stroke="#FF6600"
                      strokeWidth="1.5"
                    />
                    <circle
                      r={radius}
                      fill="#16140F"
                      stroke="#FF6600"
                      strokeWidth="1.5"
                    />
                    <text
                      textAnchor="middle"
                      dy="0.32em"
                      className="font-mono"
                      fontSize="11"
                      fontWeight="600"
                      fill="#FF6600"
                    >
                      {n.label}
                    </text>
                  </>
                ) : (
                  <>
                    <circle
                      r={radius}
                      fill="#F4F1DB"
                      stroke="#16140F"
                      strokeOpacity={onPath ? "0.85" : "0.42"}
                      strokeWidth={onPath ? "1.4" : "1"}
                    />
                    <text
                      textAnchor="middle"
                      dy="0.32em"
                      fontSize="11"
                      fontWeight="600"
                      fill="#16140F"
                      className="font-mono"
                    >
                      {n.label}
                    </text>
                    {n.tag ? (
                      <text
                        textAnchor="middle"
                        y={radius + 14}
                        fontSize="9"
                        fill="#463325"
                        className="font-mono uppercase"
                        style={{ letterSpacing: "0.16em" }}
                      >
                        {n.tag}
                      </text>
                    ) : null}
                  </>
                )}
              </g>
            );
          })}
        </g>

        {/* === Floating quote (foreignObject for selectable text) === */}
        <foreignObject
          x={QUOTE_X - 240}
          y={QUOTE_Y}
          width="400"
          height="120"
        >
          <div
            className={
              "fgh-quote " + (revealed ? "fgh-quote-shown" : "")
            }
            style={{
              opacity: revealed ? 1 : 0,
              transition: "opacity 600ms ease-out 1.4s",
            }}
          >
            <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-accent-text mb-1.5">
              you
            </div>
            <p className="font-display italic text-[20px] sm:text-[24px] leading-tight text-ink">
              &ldquo;{QUOTE_TEXT}&rdquo;
            </p>
          </div>
        </foreignObject>

        {/* === Target profile chip (selectable) === */}
        <foreignObject
          x={TARGET_CHIP_X}
          y={TARGET_CHIP_Y}
          width="280"
          height="160"
        >
          <div
            className="fgh-target-chip"
            style={{
              opacity: revealed ? 1 : 0,
              transform: revealed ? "translateY(0)" : "translateY(8px)",
              transition:
                "opacity 500ms ease-out 2.1s, transform 500ms cubic-bezier(0.16, 1, 0.3, 1) 2.1s",
            }}
          >
            <div className="rounded-md border border-ink/20 bg-bg shadow-sm p-3">
              <div className="flex items-center justify-between gap-2 mb-1.5">
                <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-accent-text">
                  matchmaker pick
                </span>
                <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted tabular-nums">
                  match {TARGET_PROFILE.matchScore}
                </span>
              </div>
              <p className="font-display text-[18px] leading-tight text-ink">
                {TARGET_PROFILE.name}
              </p>
              <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted mt-1">
                {TARGET_PROFILE.role}
              </p>
              <div className="mt-2.5 flex flex-wrap gap-1">
                {TARGET_PROFILE.tags.map((t) => (
                  <span
                    key={t}
                    className="font-mono text-[9px] uppercase tracking-[0.14em] text-muted border border-border px-1.5 py-0.5"
                  >
                    {t}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </foreignObject>
      </svg>

      {/* Caption strip below the SVG */}
      <div className="mt-5 flex items-center justify-between gap-3 text-xs">
        <span className="font-mono uppercase tracking-[0.18em] text-muted/80">
          30 of 6,000 in the YC SS 2026 graph · matchmaker traverses
          friends-of-friends to find the answer
        </span>
        <span className="hidden sm:inline font-mono uppercase tracking-[0.18em] text-accent-text">
          path: YOU → AT → SK → MAYA
        </span>
      </div>

      {/* Inline animation styles (path pulse + node breath) */}
      <style jsx>{`
        @keyframes fghPulse {
          0%, 100% {
            stroke-opacity: 0.78;
          }
          50% {
            stroke-opacity: 1;
          }
        }
        .fgh-revealed line {
          animation: fghPulse 3.6s ease-in-out infinite;
          animation-delay: 2.4s;
        }
        @media (prefers-reduced-motion: reduce) {
          .fgh-revealed line {
            animation: none;
          }
        }
      `}</style>
    </div>
  );
}
